### ISSUE TITLE
Leaking illegal actions in SampledEfficientZero

### ISSUE THREAD

**Issue by Kostyansa** [opendilab/LightZero#100]
When using SampledEfficientZero implementation there is leaking Illegal Actions in node expand on roots if amount of legal actions is less than number of sampled actions.

[In this line](https://github.com/opendilab/LightZero/blob/38524ba2a99c76f1ca6a5080465b179a63d33da4/lzero/mcts/ptree/ptree_sez.py#L122C1-L122C102):
sampled_actions = torch.multinomial(prob, self.num_of_sampled_actions, replacement=False)
If size of non-zero elements in prob is less than self.num_of_sampled_actions torch.multinomial chooses the actions 1, 2, 3, ... until the amount is equal to self.num_of_sampled_actions.

Which then can lead to model choosing illegal actions, failing of assertions and other negative things. This is particulary problematic when using SampledEfficientZero on tasks with finite amount of actions that can decrease like board games.

**Comment by puyuan1996** [comment]
Hello, thank you very much for your interest. 

Please note that the `SampledEfficientZero` algorithm implemented in LightZero currently supports environments with fixed discrete action spaces, such as Atari, as well as environments with continuous action spaces like MuJoCo. 

We haven't yet adapted the algorithm for board game environments with variable action spaces. We expect to make these adjustments around the end of October.  

However, if you currently have a need for this functionality, we warmly welcome your participation and contribution. We can discuss and address any potential adaptation issues together in this issue thread. We look forward to your contributions, and deeply appreciate your support.

Wishing you all the best.

**Comment by Kostyansa** [comment]
To give some context and tried solutions to the problem:
1) Limiting the amount of sampled actions inside the aforementioned expand function breaks the homogeneity of child_sampled_actions_segment inside the GameSegment and child_sampled_actions_batch inside the _learn_forward in SampledEfficientzero Policy
2) Accurately limiting reassigning of legal_actions inside the aforementioned expand function to block the expanding of illegal action nodes seems to work, but my experiments right now are inconclusive, it can be a good enough temporary solution if you need the functionality right now.

**Comment by Kostyansa** [comment]
Looks like Commit [e32e495e](https://github.com/opendilab/LightZero/commit/e32e495ee5c8e948a12515bf3f6f953a1358fea4) solved this issue.
