### ISSUE TITLE
AttributeError: 'SampledEfficientZeroPolicy' object has no attribute 'inverse_scalar_transform_handle'

### ISSUE THREAD

**Issue by duxtinto** [opendilab/LightZero#121]
## Steps to reproduce it:

1. prepare a sampled efficient zero mlp policy that will be used just to collect episodes. e.g:
![image](https://github.com/opendilab/LightZero/assets/333268/14cd79c7-b21b-403c-b5a8-41efdbee19b2)

2. call the forward method of the collect_mode attribute. e.g:
![image](https://github.com/opendilab/LightZero/assets/333268/2b3d1a4b-1194-430a-a1f0-ee265cad508b)

## What should happen?

the  forward method returns the policy_output

## What's happening?

this AttributeError is thrown, and the application exit with code 1:
![image](https://github.com/opendilab/LightZero/assets/333268/d8074b0c-7edb-418c-9c36-1d9a4e5bbd06)

## What do I think is happening?

I found that the `self.inverse_scalar_transform_handle` is only set on the _init_learn method:
![image](https://github.com/opendilab/LightZero/assets/333268/167093c6-9ebb-4e37-9d09-57bb824304aa)

based on that knowledge, I see 3 options here:

a) the collect mode can't be used without the learn mode
b) self.inverse_scalar_transform_handle attribute should be set for the scenarios where the learn mode is not enabled
c) we have to adapt the _forward_collect method, so it only uses the inverse_scalar_transform_handle whenever it's available. e.g.
```
            if hasattr(self, 'inverse_scalar_transform_handle'):
                pred_values = self.inverse_scalar_transform_handle(pred_values).detach().cpu().numpy()
```
Which one do you consider is the right approach?

Thanks

**Comment by puyuan1996** [comment]
- Hello, if your main goal is to use the policy in `collect_mode` for episode collection, keep in mind that the collected data will usually be utilized for learning and training. 

- Consequently, value transformations are usually required, as indicated by: "`pred_values = self.inverse_scalar_transform_handle(pred_values).detach().cpu().numpy()`". Hence, a common recommended approach is `(b)`: initialize an `InverseScalarTransform` object in the `_init_collect()` method, as depicted below:
```python
self.inverse_scalar_transform_handle = InverseScalarTransform(
    self._cfg.model.support_scale, self._cfg.device, self._cfg.model.categorical_distribution
)
```

- If you want to delve deeper into the principles behind value transformations, you could refer to the corresponding academic paper. [This paper](https://arxiv.org/abs/1805.11593) offers a comprehensive theoretical basis and case studies, providing significant support in understanding and applying value transformation techniques. 

- Of cource, If the collected data is not used for learning, you can consider alternative solution `(c)`.

**Comment by duxtinto** [comment]
Hi @puyuan1996 !

Thank you very much for the detailed information!

I will follow with (b).

Best regards,

David.
