### ISSUE TITLE
Adding Code-Of-Conduct File to the repo

### ISSUE THREAD

**Issue by mohitd404** [opendilab/LightZero#125]
As this repo is open source having a code-of-conduct File Becomes Important:- code-of-conduct:- We propose adding a comprehensive Code of Conduct to our repository to ensure a safe, respectful, and inclusive environment for all contributors and users. This code will 
serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a wider range of perspectives.

**Issue type**

- [✅] Docs

If you were planning this issue kindly assign it to me! I would love to work on it ! Thank you !

**Comment by puyuan1996** [comment]
Thanks for your valuable contribution in [PR127](https://github.com/opendilab/LightZero/pull/127)! If you have any other questions, feel free to contribute. Best wishes!
