### ISSUE TITLE
Adding Contributors Section in readme.md

### ISSUE THREAD

**Issue by mohitd404** [opendilab/LightZero#126]
Why Contributors section:- A "Contributors" section in a repo gives credit to and acknowledges 
the people who have helped with the project, fosters a sense of community, and helps others
 know who to contact for questions or issues related to the project.

**Issue type**

- [✅] Docs

Expected Outcome :- 
![7](https://github.com/opendilab/LightZero/assets/146939900/d15d5ef9-6731-4453-9311-0790265c2554)

 If you were planning this issue kindly assign it to me! I would love to work on it ! Thank you !

**Comment by puyuan1996** [comment]
Hello, we greatly appreciate your involvement and contribution. We cordially invite you to submit a Pull Request (PR) to add a "Contributors" subsection in the [Acknowledgments ](https://github.com/opendilab/LightZero#acknowledgments) section of both README.md and README.zh.md. We look forward to your valuable contribution. Best wishes.

**Comment by puyuan1996** [comment]
This issue has been soved in https://github.com/opendilab/LightZero/pull/132.
