### ISSUE TITLE
 No module named 'lzero.worker.gumbel_muzero_collector'

### ISSUE THREAD

**Issue by lewis841214** [opendilab/LightZero#143]
When trying to run gumbel_muzero:
python3 ./zoo/board_games/tictactoe/config/tictactoe_gumbel_muzero_bot_mode_config.py
on the main branch, this error pop out. 
And it seems that  there's no 'gumbel_muzero_collector" under "/zero/worker/".

Thanks!

**Comment by puyuan1996** [comment]
Hello, you're absolutely correct, this was indeed a bug. We have now rectified and resolved the issue in [this](https://github.com/opendilab/LightZero/pull/144) pull request. We deeply appreciate your contribution. Thank you.
