### ISSUE TITLE
gumbel_muzero error

### ISSUE THREAD

**Issue by lewis841214** [opendilab/LightZero#145]
when running:
python3 ./zoo/box2d/lunarlander/config/lunarlander_disc_gumbel_muzero_config.py

It will pop out the following error:

  File "/home/mtk24393/1project/LightZero-main/lzero/policy/gumbel_muzero.py", line 561, in _forward_collect
    for i, env_id in enumerate(ready_env_id):
TypeError: 'float' object is not iterable

It seems that ready_env_id == 0.0 in this case, 

So by changing:

`
            if ready_env_id is None:
                ready_env_id = np.arange(active_collect_env_num)
            # print('ready_env_id', ready_env_id)
            for i, env_id in enumerate(ready_env_id):
`
to:

`
            if ready_env_id is None or ready_env_id == 0.0:
                ready_env_id = np.arange(active_collect_env_num)
            # print('ready_env_id', ready_env_id)
            for i, env_id in enumerate(ready_env_id):
`
The error is gone.

**Comment by puyuan1996** [comment]
Hello, we have implemented the fix in this Pull Request (https://github.com/opendilab/LightZero/pull/144). Could you please pull the latest version of the main branch and run the program? We appreciate your patience.
