### ISSUE TITLE
A typo in the comment of _ucb_score

### ISSUE THREAD

**Issue by gohsyi** [opendilab/LightZero#157]
https://github.com/opendilab/LightZero/blame/3d8fb0b22249aec9e80b7eeac80b83df2b68710f/lzero/mcts/ptree/ptree_az.py#L405

N(\text{parent}) should be \sqrt{N(\text{parent})}

**Comment by puyuan1996** [comment]
Hello, thank you very much for your attention and feedback. We will fix this error in future updates. If you have any suggestions for improvement, please feel free to provide them. Best wishes!
