### ISSUE TITLE
Does `downsample = True` lead to masking input data?

### ISSUE THREAD

**Issue by ekiefl** [opendilab/LightZero#175]
For large input dimensions like Atari, it is mentioned in the codebase that the `downsample` parameter is set to `True`. I want to use `downsample = True` for my custom environment, since the `SampledEfficientZeroModel` requires hundreds of Gb of memory otherwise.

But before using this parameter, I would like to understand it. Does it end up masking my input data by deciding that certain pixels are not important? Or does the downsampling occur within latent states? In general, what are the consequences of downsampling?

On a related note, I have many other conceptual questions like this, but I'm not sure whether an issue report is the correct place to ask them. Is there a better forum to ask these questions?

Thanks for the great work at opendilab 👍

**Comment by puyuan1996** [comment]
- Hello, for the purpose of using a downsampling network, please refer to `Appendix F Network Architecture` in the original [MuZero paper](https://arxiv.org/abs/1911.08265) for specific methods and network structures. Essentially, it involves transforming high-resolution observations (e.g., 96x96) into smaller resolution latent states (e.g., 6x6) through the use of convolutional and residual blocks, without explicitly masking out unimportant pixels.

- If you have further discussions regarding the principles of the algorithm, you are welcome to raise them directly in the issues section on GitHub which will be labeled as `discussion`, or participate in discussions in the [LightZero project's general discussion forum](https://github.com/opendilab/LightZero/discussions/categories/general). Additionally, you can contact us via email at opendilab@pjlab.org.cn. Thank you for your interest.
