### ISSUE TITLE
how to test after trianing ?

### ISSUE THREAD

**Issue by valkryhx** [opendilab/LightZero#189]
A simple question about quick-start example of this wonderful project :
I modifed max_env_step = int(1e4)# int(1e5)  and successfully ran the training part.
[update]
I finally found the saved best model checkpoint tar file, and successfully ran the eval code to see the mean reward results. And my new question is how to run the saved best model with the environment to play a game[even once ] , so I can get the output list  of  [obs, reward,done,truncated,info] ? I think it's a very basic need for a new begginer, hope you teams can add some codes about the naive and essential game test code  in the quick start example.  I believe the test codes are already in the eval codes but I find it hard to simplify it. Thank you in advance.

**Comment by puyuan1996** [comment]
Hello, thank you for your suggestion. Please refer to the test file [here](https://github.com/opendilab/LightZero/blob/main/lzero/mcts/tests/test_game_segment.py#L108). You will need to adjust the `evaluator_env_num` parameter in the corresponding test configuration file (located at [here](https://github.com/opendilab/LightZero/blob/main/lzero/mcts/tests/config/tictactoe_muzero_bot_mode_config_for_test.py#L8)) to 1 and add a `model_path` parameter to [here](https://github.com/opendilab/LightZero/blob/main/lzero/mcts/tests/config/tictactoe_muzero_bot_mode_config_for_test.py#L40) , specifying the path to your model checkpoint (something like `model_path="./ckpt/ckpt_best.pth.tar",`) to meet your requirements. We will later consider simplifying this into a more beginner-friendly exampleBest wishes!

**Comment by valkryhx** [comment]
Thank you for your detailed reply, but still here remains some issues. In short , after following the instructions above, the learned model seems to act randomly in the test code. But in the eval part, it indeed output to get the reward as expected.

**Comment by puyuan1996** [comment]
> after training, model eval result is ok ,but in test codes ,the model seems to acts randomly? #193

Hello, this question has been answered here. Thank you.
