### ISSUE TITLE
connect 4 setup bugs 

### ISSUE THREAD

**Issue by drblallo** [opendilab/LightZero#203]
on the latest commit,  77bbac05880ea84e7748b0f898a714494bd1fb93

connect 4 is broken with various setup

python -u zoo/board_games/connect4/config/connect4_muzero_sp_mode_config.py
and
python -u zoo/board_games/connect4/config/connect4_muzero_bot_mode_config.py

crashes with
```
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[5, 6, 7, 3] to have 3 channels, but got 6 channels instead
```

while

python -u zoo/board_games/connect4/config/connect4_alphazero_bot_mode_config.py

crashes with
```
AttributeError: 'EasyDict' object has no attribute 'prob_random_action_in_bot'
```

**Comment by puyuan1996** [comment]
Hello, thank you for your feedback! This issue has been fixed in the latest [main branch](https://github.com/opendilab/LightZero/commit/29c9afd4dc631ff568984ddeacca3d4ce4e29065). Best wishes!
