### ISSUE TITLE
Inconsistency Between Episode Counts in MuZero

### ISSUE THREAD

**Issue by LGXHTM** [opendilab/LightZero#205]
when running the cartpole_muzero_config.py, get_world_size() returns 1, indicating there should only be one process (the machine has one CPU and one GPU), but the total number of episodes in the buffer is twice the number recorded by the main process(The sum of the 'episode_count' from the main process, not the number of 'self._total_envstep_count'). What could be the issue? 
Additionally,In the collect function of MuZero, I noticed that upon the completion of each episode, both self._total_episode_count and collected_episode are incremented by 1. Then, at the end of the code block,
`        if self._world_size > 1:
            collected_step = allreduce_data(collected_step, 'sum')
            collected_episode = allreduce_data(collected_episode, 'sum')
            collected_duration = allreduce_data(collected_duration, 'sum')
        self._total_envstep_count += collected_step
        self._total_episode_count += collected_episode
        self._total_duration += collected_duration`
Subsequently, 'self._total_episode_count' is incremented again by the value of 'collected_episode'. Does this lead to duplicate counting?Adding this will ensure alignment with the number of episodes in the buffer.
Your help would be greatly appreciated.

**Comment by puyuan1996** [comment]
Hello, thank you for your feedback! This issue has been fixed in the latest [main branch](https://github.com/opendilab/LightZero/commit/5fc7c4583553943d81e5d2035415e000db5acf9f). Best wishes!
