### ISSUE TITLE
The multi-GPU issue

### ISSUE THREAD

**Issue by LGXHTM** [opendilab/LightZero#214]
When running the command 'python3 -u zoo/atari/config/atari_muzero_multigpu_ddp_config.py', I encountered an error:
`File "zoo/atari/config/atari_muzero_multigpu_ddp_config.py", line 116, in <module>
    with DDPContext():
  File "/home/x/anaconda3/envs/lz/lib/python3.8/site-packages/ding/utils/pytorch_ddp_dist_helper.py", line 215, in __enter__
    dist_init()
  File "/home/x/anaconda3/envs/lz/lib/python3.8/site-packages/ding/utils/pytorch_ddp_dist_helper.py", line 164, in dist_init
    raise RuntimeError("please indicate rank explicitly in dist_init method")
RuntimeError: please indicate rank explicitly in dist_init method`
In the case where there are 4 GPUs, how can this issue be resolved?

**Comment by puyuan1996** [comment]
Hello! Are you starting the program following the format specified [here](https://github.com/opendilab/LightZero/blob/main/zoo/atari/config/atari_muzero_multigpu_ddp_config.py#L111)?
