### ISSUE TITLE
Custom environment

### ISSUE THREAD

**Issue by Depresivna-ryza** [opendilab/LightZero#219]
The tutorial for creating a custom environment describes how to add the environment. However, It doesn't mention how to start the RL algorithms on it. Is there some guideline I can follow to test my environment on various algorithms? Also, how can I use AlphaZero, since it assumes a perfect simulator inside its mcts ?

**Comment by puyuan1996** [comment]
Hello, thank you for your patience. Regarding how to test one environment on various algorithms, we have provided a brief instruction on setting up the config file [here](https://github.com/opendilab/LightZero/blob/main/docs/source/tutorials/config/config.md), hoping to be helpful to you.

Regarding the use of AlphaZero, indeed as you mentioned, it requires the environment to have a perfect simulator. Specifically, like the board game environment, it needs to have the capability to `reset(state)`, you can refer to the [implementation](https://github.com/opendilab/LightZero/blob/main/zoo/board_games/gomoku/envs/gomoku_env.py#L168) of the Gomoku environment. Therefore, if you want to apply AlphaZero to a custom environment, you need to ensure that your environment can implement this function. If the environment does not meet these conditions, you might not be able to use AlphaZero. As an alternative, you could consider using the [MuZero algorithm](https://github.com/opendilab/LightZero/blob/main/zoo/atari/config/atari_muzero_config.py), which conducts MCTS within the learned model. You can refer to the specific details in the MuZero research [paper](https://arxiv.org/abs/1911.08265).

We hope this information is helpful to you! If you have other questions or need further guidance, please feel free to contact us. Thank you again for your attention and support!
