### ISSUE TITLE
Does LightZero currently support compilation on Windows?

### ISSUE THREAD

**Issue by valkryhx** [opendilab/LightZero#222]

**Comment by puyuan1996** [comment]
Hello, thank you for your question. However, I apologize as we have not yet tested on Windows, but we plan to do so in the coming days. You can also post any error messages you encounter during local compilation here, and we can discuss how to resolve these issues together.

**Comment by valkryhx** [comment]
The c++ codes contains some .h lib which only exist on Linux , so the compilation fails.
But when the c++ codes are excluded , the python codes work well.
This is the test result on win, fyi.

**Comment by lunathanael** [comment]
I would like to comment, using WSL2, Compiling and using the library proved to have no problems.
