### ISSUE TITLE
Replicating multi-GPU EfficientZero Atari results

### ISSUE THREAD

**Issue by selfsim** [opendilab/LightZero#223]
Hello,

I want to replicate all E0 Atari results to compare my custom learner against. 

I have SSH access to 32 CPU core + 4 GPU nodes on a cluster.  I managed to get the single GPU `atari_efficientzero_config.py` to work, but I have been unable to run the multi-GPU `atari_efficientzero_multigpu_ddp_config.py` successfully. Can you confirm that the latter works on the current  version? And if so, can you provide the environment details (python version etc.) and the execution instructions used? 

Also, do you have the hyperparameters for the E0 Atari trials? I'm assuming they are all default but it would be nice to have confirmation.

**Comment by puyuan1996** [comment]
Hello, we have confirmed that the file `atari_efficientzero_multigpu_ddp_config.py` on the main branch can be run normally using the following command:

```bash
python -m torch.distributed.launch --nproc_per_node=2 zoo/atari/config/atari_efficientzero_multigpu_ddp_config.py
```

The environment configuration is as follows:
- python==3.9.12
- gym==0.25.1
- ale-py==0.8.0

Could you please specify the error message you are encountering? Regarding the hyperparameters for EfficientZero, you can use the default settings. If necessary, you can also adjust parameters such as [model_update_ratio](https://github.com/opendilab/LightZero/blob/main/lzero/policy/efficientzero.py#L117) to optimize performance. I hope this information is helpful to you!
