### ISSUE TITLE
Minigrid environment

### ISSUE THREAD

**Issue by Depresivna-ryza** [opendilab/LightZero#225]
I was looking at the implementation of the minigrid environment as inspiration to create my own environment. I noticed that the correspoin efficient muzero config doesnt actually use the environment. In fact it can be removed entirely and efficient muzero runs normally. Is this intended ?

**Comment by puyuan1996** [comment]
Hello, what exactly does it mean by "efficient muzero config doesn't actually use the environment"? Our [configuration](https://github.com/opendilab/LightZero/blob/main/zoo/minigrid/config/minigrid_efficientzero_config.py#L80) definitely uses this [minigrid environment](https://github.com/opendilab/LightZero/blob/main/zoo/minigrid/envs/minigrid_lightzero_env.py). Could you please provide more details about the issue? Thank you.
