### ISSUE TITLE
Running a trained agent

### ISSUE THREAD

**Issue by zbeucler2018** [opendilab/LightZero#228]
Hello! First off this repo is awesome so thank you for all your hard work! I recently ran the quick start for TicTacToe but I am not sure how to run and watch the trained agent

**Comment by puyuan1996** [comment]
Hello, thank you for your question. You can directly run this [configuration file](https://github.com/opendilab/LightZero/blob/main/zoo/board_games/tictactoe/entry/tictactoe_muzero_eval.py), just modify this [line](https://github.com/opendilab/LightZero/blob/main/zoo/board_games/tictactoe/entry/tictactoe_muzero_eval.py#L22) to the path of your actual trained checkpoint. Additionally, you can refer to the following links for more information: [Issue 189](https://github.com/opendilab/LightZero/issues/189), [Issue 193](https://github.com/opendilab/LightZero/issues/193), [Log Tutorial](https://github.com/opendilab/LightZero/blob/main/docs/source/tutorials/logs/logs_zh.md). 
Feel free to ask any further questions. Best wishes!

**Comment by zbeucler2018** [comment]
Thank you!
