### ISSUE TITLE
Render and plot results: is there a code snippet?

### ISSUE THREAD

**Issue by marintoro** [opendilab/LightZero#231]
Hello,

I was just wondering if and where is the code to render and plot the results after an experiment?
For exemple, the code used to generate all the curves in the README.md.

I found a code to plot a MCTS tree, `plot_simulation_graph` in `mcts/utils.py` which is very convenient (maybe there should be somewhere a documentation for all the debug tool available?) but I can't find a similar code to plot proper curves from logs (i.e. the folder `logs/evaluator` and `logs/collector`).

**Comment by puyuan1996** [comment]
Hello, thank you for your attention. Our plotting code is essentially similar to the example provided [here](https://github.com/opendilab/DI-toolkit?tab=readme-ov-file#create-multi-seed-multi-algorithm-benchmark-plots). You can test it, and if there are any issues, feel free to reach out at any time. Best wishes.
