### ISSUE TITLE
Could you provide detail code example to customize the env and algo that can run successfully in a entire file?

### ISSUE THREAD

**Issue by yuuma002** [opendilab/LightZero#236]
We have read the docs carefully. However, we cannot find such example. All we can find is:

https://github.com/opendilab/LightZero/blob/main/docs/source/tutorials/envs/customize_envs_zh.md

What we want is the code example that can run successfully in a entire files with customized envs, which is not by the config files (e.g. zoo/classic_control/cartpole/config/cartpole_muzero_config.py)

Could you provide detail code example to customize the env and algo that can run successfully in a entire file?

Thank a lot.

**Comment by PaParaZz1** [comment]
You can refer to our previous pull request about adding a new environment. Such as:
- [Memory Env](https://github.com/opendilab/LightZero/pull/197)
- [MountainCar Env](https://github.com/opendilab/LightZero/pull/181)
- [2048 Env and Stochastic MuZero](https://github.com/opendilab/LightZero/pull/64)
- [Connect4 Env](https://github.com/opendilab/LightZero/pull/63)

If you have any other questions, please feel free to ask in this issue.

**Comment by PaParaZz1** [comment]
Typically, you do not need to refer to the source code of DI-engine (ding); simply following the examples we provide should suffice. However, if you encounter issues that you are unable to resolve, you may consult the `policy/model/env` sections of DI-engine or seek assistance by posting issues in LightZero.

**Comment by yuuma002** [comment]
Could you provide detail docs of the classes we should used in building RL algorithms?

We find some classes lacks docs in https://di-engine-docs.readthedocs.io/en/latest/01_quickstart/first_rl_program.html:
- StepCollector
- eps_greedy_handler
- interaction_evaluator
- ...

This makes it diffucult to understand the quickstart tutorial.

Hope you can fix the issue.

Thanks.

**Comment by PaParaZz1** [comment]
LightZero uses our **old** pipeline of DI-engine while the quickstart doc of DI-engine has already presented our **new** pipeline. 
- Here is the [doc](https://di-engine-docs.readthedocs.io/zh-cn/latest/04_best_practice/diff_in_new_pipeline_zh.html) (in Chinese, if necessary, we will add the English version next week) about their difference.
- Here is the [doc](https://di-engine-docs.readthedocs.io/en/latest/05_api_doc/framework/middleware/index.html) about the concrete API definition of middlewares (e.g. eps_greedy_handler) in new pipeline.
- Here is the [doc](https://di-engine-docs.readthedocs.io/en/latest/05_api_doc/worker/collector/index.html) about the concrete API definition of modules in old pipeline.

**Comment by yuuma002** [comment]
When will the docs be completed (e.g. https://di-engine-docs.readthedocs.io/en/latest/05_api_doc/framework/middleware/functional/explorer.html#eps-greedy-handler)?

![image](https://github.com/opendilab/LightZero/assets/110771404/8de8a500-6423-4169-9c6f-7058a3a603e6)

**Comment by PaParaZz1** [comment]
> When will the docs be completed (e.g. https://di-engine-docs.readthedocs.io/en/latest/05_api_doc/framework/middleware/functional/explorer.html#eps-greedy-handler)?
> 
> ![image](https://private-user-images.githubusercontent.com/110771404/341666789-8de8a500-6423-4169-9c6f-7058a3a603e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNDc0MzEsIm5iZiI6MTcxOTA0NzEzMSwicGF0aCI6Ii8xMTA3NzE0MDQvMzQxNjY2Nzg5LThkZThhNTAwLTY0MjMtNDE2OS05YzZmLTcwNThhM2E2MDNlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQwOTA1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjQwMzE1NTU2OGE0YmJkYTY5MmVkOTdjMjYwZTgyODNjNDY1NjA0Yzg2ZDRlOWYyY2M5ZjA3N2RhOGFjMzMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gJhEUjTa_4i1Ow7z7C8L3tR3kmCc2eWcvywtmGu4mS0)

We have fixed this problem in the latest commit of DI-engine. It is a import bug resulting in the wrong doc format. Now you can visit the corresponding API doc with this doc [link](https://opendilab.github.io/DI-engine/05_api_doc/framework/middleware/functional/collector.html).
