### ISSUE TITLE
Issues related to the operating environment

### ISSUE THREAD

**Issue by he-cw** [opendilab/LightZero#244]
Hello!
I would like to inquire if it still cannot run on the Windows system at the moment？
Thanks！

**Comment by puyuan1996** [comment]
Hello, we have not conducted tests on Windows previously. Have you encountered any error messages while running it on Windows? If so, please share them with us here, and we can debug together. We will also be testing on a local Windows system in the near future and will share relevant information here.

**Comment by he-cw** [comment]
您好，我已收到您的邮件，我会尽快阅读！

**Comment by he-cw** [comment]
I encountered an error while running: ModulaNotFoundError: No module named 'ding'

I am using the latest Python 3.12.4, but couldn't find a module with the exact name 'ding' in Pypi

Is there any problem with my operation？

**Comment by he-cw** [comment]
Thank you！
