### ISSUE TITLE
Need Help with Storing and Using Best Checkpoint with ONNX Model in LightZero

### ISSUE THREAD

**Issue by moganli** [opendilab/LightZero#249]
Hello LightZero community,
﻿
I'm currently working on a project where I need to store and use the best checkpoint using an ONNX model. However, I'm facing some difficulties in implementing this.bu
Do you have any plans to support  onnx model in the future?

**Comment by puyuan1996** [comment]
Hello, we currently do not have plans to adapt the ONNX model in the near future. However, you can submit any issues you encounter during the adaptation process in this issue area, and we can discuss and resolve them together. If conditions permit, we also warmly welcome you to submit a PR for adapting the ONNX model for LightZero. Thank you for your support.
