### ISSUE TITLE
cannot import name 'ez_tree' from 'lzero.mcts.ctree.ctree_efficientzero' (D:\LightZero-main\LightZero-main\lzero\mcts\ctree\ctree_efficientzero\__init__.py)

### ISSUE THREAD

**Issue by MMScn** [opendilab/LightZero#25]
Hello!
When I run _cartpole_muzero_config.py_ ,somethong wrong~  o.O
Do you know how to fix this?

cannot import name 'ez_tree' from 'lzero.mcts.ctree.ctree_efficientzero' (D:\LightZero-main\LightZero-main\lzero\mcts\ctree\ctree_efficientzero\__init__.py)

**Comment by puyuan1996** [comment]
Hello, thank you very much for your question.
This error is caused by not being able to correctly import the Cython extension module.
Have you already run pip install -e . in the LightZero directory? This command will automatically find the corresponding Cython extensions and compile them. Did you encounter any errors when executing this step? Please note that only Linux and macOS are currently supported.

**Comment by MMScn** [comment]
Thank you so very very much for your reply!
I found that the reason for this error was that I was using the Windows operating system.
Best Wishes.

**Comment by puyuan1996** [comment]
Hello, 

The reason why we currently do not support Windows is that there are still issues with compiling cython on Windows, which we are working to resolve. 

A temporary workaround is to set
`policy=dict(mcts_ctree=False, ...) # setting this to False means using ptree, which does not require cython compilation.`
in [cartpole_muzero_config.py](https://github.com/opendilab/LightZero/blob/main/zoo/classic_control/cartpole/config/cartpole_muzero_config.py) to use ptree in the MuZero algorithm.

Best Wishes.

**Comment by xiezhipeng-git** [comment]
Does WSL not support this as well? I'm also getting this error in my WSL2. Hope it can be supported on Windows soon.

**Comment by puyuan1996** [comment]
Regrettably, we currently do not offer support for compilation on the Windows operating system. We anticipate resolving this issue in approximately one month's time. Until then, we recommend following the interim solution provided [here](https://github.com/opendilab/LightZero/issues/25#issuecomment-1537353753)  , or if possible, switching to an operating system that satisfies the necessary requirements.

We greatly appreciate your patience and understanding during this period.

Best regards.

**Comment by marcusbeyond** [comment]
> Hello,
> 
> The reason why we currently do not support Windows is that there are still issues with compiling cython on Windows, which we are working to resolve.
> 
> A temporary workaround is to set `policy=dict(mcts_ctree=False, ...) # setting this to False means using ptree, which does not require cython compilation.` in [cartpole_muzero_config.py](https://github.com/opendilab/LightZero/blob/main/zoo/classic_control/cartpole/config/cartpole_muzero_config.py) to use ptree in the MuZero algorithm. Compared to ctree, its speed will be about 3 times slower.
> 
> Best Wishes.

Hello,
I've just tried your solution (workaround) and unfortunately it doesn't work. Setting the `mcts_ctree=False` flag is not enough to make it work.

It looks like the conflicting file is: `LightZero-main\lzero\mcts\tree_search\mcts_ctree.py`

```
from lzero.mcts.ctree.ctree_efficientzero import ez_tree as tree_efficientzero
from lzero.mcts.ctree.ctree_muzero import mz_tree as tree_muzero
from lzero.mcts.ctree.ctree_gumbel_muzero import gmz_tree as tree_gumbel_muzero
from lzero.policy import InverseScalarTransform, to_detach_cpu_numpy

if TYPE_CHECKING:
    from lzero.mcts.ctree.ctree_efficientzero import ez_tree as ez_ctree
    from lzero.mcts.ctree.ctree_muzero import mz_tree as mz_ctree
    from lzero.mcts.ctree.ctree_gumbel_muzero import gmz_tree as gmz_ctree
```

It seems to be a core file. 
Any ideas how to make it work under Windows? 
(that is: import the normal MCTS functionality and avoid importing the compiled files)
