### ISSUE TITLE
How to draw train curve

### ISSUE THREAD

**Issue by MMScn** [opendilab/LightZero#28]
Hello!
I am glad to see such a awesome open source project. 
I would like to plot a training curve like the following graph,but I have no idea how to do this, can you please tell me how to do this?
I would be very grateful
<img width="388" alt="image" src="https://github.com/opendilab/LightZero/assets/50766892/b0c17c46-409a-489c-ae71-80f615f9d23d">

**Comment by puyuan1996** [comment]
Hello, 

Thank you for your attention. We will be open-sourcing the code for creating a curve similar to the one in the benchmark within a week. We hope this will be helpful to you. 

Best regards.

**Comment by MMScn** [comment]
That is a good news!
Really looking forward to seeing the new feature.
Best regards.

**Comment by puyuan1996** [comment]
Hello,

Thank you for your patience. Currently, generating benchmark-like graphs from multiple seeds and multiple algorithm experiments using tensorboard events files has been integrated into the [DI-toolkit](https://github.com/opendilab/DI-toolkit) package. For specific usage, please refer to this PR:
https://github.com/opendilab/DI-toolkit/pull/6

Best wishes.
