### ISSUE TITLE
ZeroPal is down.

### ISSUE THREAD

**Issue by AbelHutten** [opendilab/LightZero#282]
It seems that ZeroPal is down.
![image](https://github.com/user-attachments/assets/0779cb0d-f5e8-43fc-8cb7-5cf0057751a8)

**Comment by puyuan1996** [comment]
Hello, the repair will be completed in the next few weeks. Thank you for your attention!

**Comment by puyuan1996** [comment]
Hello, the previous issue occurred because our OpenAI API key exceeded the usage limit, which caused access problems. We have now updated the key for the base model, and [access](https://huggingface.co/spaces/OpenDILabCommunity/ZeroPal) is functioning normally. Thank you for your attention!

**Comment by AbelHutten** [comment]
Great! Closing the issue :)
