### ISSUE TITLE
关于利用GPU加速MCTS

### ISSUE THREAD

**Issue by fixtech** [opendilab/LightZero#285]
请问在当前MCTS的实际部署中，是否有利用GPU加速的需求？当前的GPU加速MCTS的工作比较少，想了解下是因为MCTS本身在E2E耗时占比不高，还是说算法不太适合GPU加速处理？例如必须要有大batch才能发挥GPU的优势？

**Comment by PaParaZz1** [comment]
MCTS 这块的算法实现不太适合 GPU 加速处理，所以并行化的加速比较差。不过我们最近也在尝试其他的加速方案，您如果有兴趣的话之后或许可以一起合作。

**Comment by puyuan1996** [comment]
> 请问在当前MCTS的实际部署中，是否有利用GPU加速的需求？当前的GPU加速MCTS的工作比较少，想了解下是因为MCTS本身在E2E耗时占比不高，还是说算法不太适合GPU加速处理？例如必须要有大batch才能发挥GPU的优势？

也可以参考这里的博客哈：https://zhuanlan.zhihu.com/p/688093451。
