### ISSUE TITLE
如果想渲染环境如何设置？

### ISSUE THREAD

**Issue by ldepn** [opendilab/LightZero#287]
以cartpole为例，在训练时，如果想渲染环境如何设置？

**Comment by puyuan1996** [comment]
您好，当您运行[这个脚本](https://github.com/opendilab/LightZero/blob/main/zoo/classic_control/cartpole/config/cartpole_muzero_config.py)并得到收敛结果后，`best ckpt`文件会保存在类似以下路径的文件夹中：

```
./LightZero/zoo/classic_control/cartpole/config/data_muzero/cartpole_muzero_ns25_upc100_rer0_seed0/ckpt/ckpt_best.pth.tar
```

接下来，您只需在[这里](https://github.com/opendilab/LightZero/blob/main/zoo/classic_control/cartpole/entry/cartpole_eval.py#L21)将路径修改为您保存的 `best ckpt` 文件的实际路径，然后运行[这个脚本](https://github.com/opendilab/LightZero/blob/main/zoo/classic_control/cartpole/entry/cartpole_eval.py)。运行完成后，您可以在以下路径找到模型与环境交互生成的 GIF 回放：

```
./LightZero/zoo/classic_control/cartpole/entry/cartpole_gif
```
类似这样：
![CartPole-v0_episode_0_20241016155515](https://github.com/user-attachments/assets/6e1abb04-f51e-4ab5-a7f9-58298ca3275e)

如果您有任何问题，欢迎随时提问。
