### ISSUE TITLE
An easy way to visualize the agent ? 

### ISSUE THREAD

**Issue by MoMeAKR** [opendilab/LightZero#38]
Hello, 

I'm looking for a way to actually display what the agent does once trained. I am a bit lost in the MuzeroEvaluator class for instance. Could you provide guidance so I can try and implement some env.render there ? I'll submit a pull request if successful afterwards. 
Thanks a lot !

**Comment by puyuan1996** [comment]
Hello,

Thank you very much for your interest in our work. We are currently organizing the relevant code for rendering and saving replay, and we plan to submit a Pull Request within the next few days. We appreciate your patience.

Best wishes.

**Comment by puyuan1996** [comment]
Hello,

The example code for loading a trained model and saving the replay is now available in this [Pull Request](https://github.com/opendilab/LightZero/pull/40). To store the replay, you can ``set main_config.env.save_video = True`` in [this file](zoo/atari/config/atari_eval_config.py), and specify the path to your trained model's checkpoint file in ``model_path``.

Best wishes.

**Comment by MoMe36** [comment]
Hello ! Thanks a lot :D I'll be testing ASAP ! Thank you for your work

**Comment by puyuan1996** [comment]
Hello, 

The [Pull Request ](https://github.com/opendilab/LightZero/pull/40) related to real-time video rendering and saving replay has been merged into the main branch. Please refer to the instructions in this [file](https://github.com/opendilab/LightZero/blob/main/zoo/atari/config/atari_eval_config.py) for visualizing the agent.

Best regards.
