### ISSUE TITLE
I dream of agent playing 2048 using this library~

### ISSUE THREAD

**Issue by LinXueyuanStdio** [opendilab/LightZero#41]
May it come true?

**Comment by puyuan1996** [comment]
Hello,

Thank you very much for your attention. Yes, we are confident that this can be achieved. The[ Stochastic MuZero](https://openreview.net/forum?id=X6D9bAHhBQ1) algorithm is designed to solve environments with stochasticity in dynamics, such as 2048. We are currently developing the 2048+Stochastic MuZero algorithm, and have completed about 80% of the work. We will submit the related PR in a few weeks, so please stay tuned. Thank you for your patience.

Best wishes.

**Comment by PaParaZz1** [comment]
We are working on the implementation of Stochastic MuZero with 2048 env in #64. You can keep track of it.

**Comment by LinXueyuanStdio** [comment]
Yeah, I have been following the PR for days.

**Comment by PaParaZz1** [comment]
#77 shows some experiment results on 2048 environment.

**Comment by puyuan1996** [comment]
- Hello, we have comprehensively optimized the 2048 environment and the related training configurations for Bot, MuZero, and Stochatic MuZero in this [PR](https://github.com/opendilab/LightZero/pull/64). We are now providing the benchmark results in the 2048 environment as shown in the following image:

![image](https://github.com/opendilab/LightZero/assets/48008469/666e7902-e2f9-446a-8341-95744caf4e58)

- Furthermore, we've provide the render video to illustrate the performance of Random action, Bot action, MuZero, and Stochastic MuZero agents in the 2048 environment.

    - Random action (~1000):
![game_2048_random](https://github.com/opendilab/LightZero/assets/48008469/71293c40-54e2-4db7-8921-3c8b43760aac)

    - Bot action (~30000-70000):
![game_2048_bot_small](https://github.com/opendilab/LightZero/assets/48008469/60199351-7803-4c5e-9960-02a2a9288e76)

    - MuZero sim=100 (~27956):
![game_2048_muzero_ns100_s0](https://github.com/opendilab/LightZero/assets/48008469/6ba6eec4-7034-4ac4-a1b7-3024b71a5303)

    - Stochastic MuZero sim=100 (~37356）:
![game_2048_stochastic_muzero_ns100_s0_small](https://github.com/opendilab/LightZero/assets/48008469/4bbe8e57-d268-4b79-8dab-4b2312b11c0e)

    - Where the term `sim` represents the number of simulations used for evaluation in MCTS, and the score within brackets corresponds to the score procured by each respective agent.

Thank you for your attention.
