### ISSUE TITLE
Unrelated Records During EfficientZero in TensorBoard

### ISSUE THREAD

**Issue by seolhokim** [opendilab/LightZero#49]
Hi, thank you for your great contribution.

I ran the following command:
`python3 -u zoo/atari/config/atari_efficientzero_config.py`

Afterwards, I checked TensorBoard using the command:
`tensorboard --logdir data_ez_ctree`

I noticed that there are many unrelated Roland records written. Could you please guide me on how to prevent those results from being recorded?

**Comment by puyuan1996** [comment]
Hello,

Thank you very much for your attention.

Regarding the "unrelated Roland records" you mentioned, I'm not quite certain what it refers to. Could you please provide more context or information about this?

In LightZero, the monitoring of metrics in TensorBoard is configured using[ this method](https://github.com/opendilab/LightZero/blob/main/lzero/policy/efficientzero.py#L692). If there are any metrics you would prefer not to monitor in TensorBoard, you can easily remove the corresponding variables.

Best wishes.

**Comment by seolhokim** [comment]
sorry. I had some confusion between tensorboard ports. thank you for your real quick reply
