### ISSUE TITLE
Single Player AlphaZero

### ISSUE THREAD

**Issue by DominikRoB** [opendilab/LightZero#88]
Do you plan to support a single-player version of AZ anytime? It would be lovely to compare the different methods on similar benchmarks.

**Comment by puyuan1996** [comment]
Hello, thank you for your attention.

- Currently, in LightZero, the "play_with_bot_mode" is essentially equivalent to the "single_player" mode. You can refer to the [entry example](https://github.com/opendilab/LightZero/blob/main/zoo/board_games/tictactoe/config/tictactoe_alphazero_bot_mode_config.py) in the TicTacToe game. In the "play_with_bot_mode" mode, data collection is done through the agent playing against the bot. To the best of my knowledge, in this mode, for the AlphaZero agent, it treats the bot as part of the environment, so it is essentially a single-player mode.

- It's important to note that in the AlphaZero algorithm, during the Monte Carlo Tree Search (MCTS), the environment needs to provide a method similar to "reset(init_state)". However, this method is only applicable to board games like TicTacToe, so its applicability is limited.

- A potentially more widely applicable extension is the[ MuZero ](https://github.com/opendilab/LightZero/blob/main/lzero/policy/muzero.py)algorithm, which can run on [Atari](https://github.com/opendilab/LightZero/blob/main/zoo/atari/config/atari_muzero_config.py) environments in the "single_player" mode and also on [board game ](https://github.com/opendilab/LightZero/blob/main/zoo/board_games/tictactoe/config/tictactoe_muzero_bot_mode_config.py)environments in the "play_with_bot_mode" mode (which is equivalent to the "single_player" mode).

If you have any other questions, please feel free to ask. 

Best Wishes!

**Comment by puyuan1996** [comment]
Hello,

It's great to hear that you're interested in using reinforcement learning, specifically AlphaZero, for solving your scheduling problem. Yes, if your problem can be formulated in a way that allows for resetting the environment to an initial state using the reset(init_state) method, then it should be compatible with the AlphaZero algorithm.

I'm looking forward to seeing your specific application and discussing any questions or challenges you may encounter. Please feel free to continue the discussion in this issue. Thank you for reaching out, and I'm glad to be of assistance to you! 

Best Wishes.
