### ISSUE TITLE
Upgrade to gymnasium

### ISSUE THREAD

**Issue by redmie** [opendilab/LightZero#92]
As [gym](https://github.com/openai/gym) is no longer maintained, we should upgrade to it's recommended fork [gymnasium](https://github.com/Farama-Foundation/Gymnasium).

**Comment by puyuan1996** [comment]
I agree with your suggestion to upgrade to the latest gymnasium library. Given that gym is no longer maintained, pivoting to a more updated and actively maintained library is definitely beneficial for the long-term growth and sustainability of our project.

Thank you for bringing this to our attention and providing your valuable feedback. We plan to upgrade to the latest version of gymnasium in the coming weeks.

Best Wishes
